scenario:
  name: "tunnel"
  map_size_x: 90.0
  map_size_y: 30.0
  map_size_z: 3.5

swarm:
  drone_num: 2
  initial_poses:
    - {id: 1, topic_id: 0, x: 0.0, y: 0.0, z: 1.0}
    - {id: 2, topic_id: 1, x: 0.0, y: -1.0, z: 1.0}

planning:
  max_vel: 3.0
  max_acc: 2.5
  obstacle_inflation: 0.05

